class Resources {
  String haa;
  String saved;
  String quran;
  String tepsir;
  String oginix;
  String logat;
  String haptiyak;
  String para;
  String mundarija;
  String sura;
  String ayat;
  String tangxak;
  String kortisitiganTillar;
  String arabikHatnurshisi;
  String language;
  String hatqongliki;
  String hatqonglikiUyghur;
  String kiraat;
  String kaytix;
  String muahhmadsalih;
  String hayattarjimisi;
  String aalimTarjimiai;
  String yusupmuhahmadtarjimisi;
  String muahhmadsalihMidel;
  String hayattarjimisiMidel;
  String aalimTarjimiaiMidel;
  String yusupmuhahmadtarjimisiMidel;
  String hilTarjima;
  String bismillaah;
  String marhaba;
  String showTarjimaEnglish;
  String showTarjimaTurky;
  String showTarjimaHanyu;
  String assalam;
  String sakliwalganlar;
  String tallang;
  String tallapquxurung;
  String kiraatQuxurux;
  String quxupbolgan;
  String qiraattinioqurux;
  String ibnikasir;
  String muyassar;
  String zarif;
  String arapqisinikorsitamdu;
  String ayatkatizberix;
  String muyassarArabpa;
  String arjalalein;
  String muhtasarArapqa;
  String muhtasar;
  String muhtasarEnglish;
  String muhtasarChina;
  String muhtasarTuruk;
  String server;
  String keyinkiSura;
  String awalayattallang;
  String awarkiraatquxuring;
  String yok;
  String timilar;
  String keyinki;
  String aldinki;
  String buangaldinkisi;
  String buangahirkisi;
  String kiskusakoxuldi;
  String kiskustinoquruldi;
  String okupkalganjaysaklandi;
  String saklanganorunyok;
  String saklangalaryok;
  String uqur;
  String aldinkiSaklapkoyganjaydinbaxlapokumsiz;
  String jalalein;
  String tapsilatiniKuramsi;
  String nosuraaya;
  String hatnurshisi;
  String dualar;
  String search;
  String search1;
  String kirixsoz;
  String naqijaTepildi;
  String rang;
  String bat;
  String birayatkoyuxhalitigaalmaxti;
  String kopyatkoyuxhalitigaalmaxti;
  String qurandikiTimilar;
  String muansiwatlikAyatlar;
  String bax;
  String qurandikimazmunlarniuginix;
  String angusti;
  String tima;

  String hanzuqatapsir;

  String koquruldi;

  String haripboyqaizdax;

  String daris;
  setLang(String lang) {
    daris = "دەرس";
    haripboyqaizdax = "ھەرپ بويىچە ئىزدەش";
    koquruldi = "كۆچۈرۈلدى";
    hanzuqatapsir = "خەنزۇچە تەپسىر";
    tima = "تىما";
    angusti = "ئەڭ ئۈستى";
    qurandikimazmunlarniuginix =
        "قۇرئان كەرىمنى تېمىلار ( مەزمۇنلار) غا ئاساسەن ئۆگىنىش";
    bax = "باش";
    muansiwatlikAyatlar = "مۇناسىۋەتلىك ئايەتلەر";
    qurandikiTimilar = "قۇرئاندىكى تىمىلار";
    birayatkoyuxhalitigaalmaxti = "بىرلا ئايەت قويۇشقا ئالماشتى";
    kopyatkoyuxhalitigaalmaxti = "ئارقىمۇ ئارقا قويۇشقا ئالماشتى";
    bat = "بەت";
    rang = "رەڭ";
    naqijaTepildi = "نەتىجە تېپىلدى";
    kirixsoz = "كېرىش سۆز";
    search = "ئـــــىـــــــــــــــــــــــزدەش";
    search1 = "ئىزدەش";
    dualar = "دۇئالار";
    marhaba = "مەرھابا";
    nosuraaya = "سۈرە ياكى ئايەتنى پەرىقلەندۈرەلمىدى";
    tapsilatiniKuramsi = "تەپسىلاتىنى كۆرەمسىز؟";
    jalalein = "جالالىيىن";
    aldinkiSaklapkoyganjaydinbaxlapokumsiz =
        "ئالدىنقى ساقلاپ قويغان جايدىن باشلاپ ئوقۇمسىز؟";
    uqur = "ئۇچۇر";
    saklanganorunyok = "ئوقۇپ كەلگەن جاي يوق";
    okupkalganjaysaklandi = "ئوقۇپ كەلگەن جاي ساقلاندى";
    saklangalaryok = "قىسقۇچتا ھېچنىمە يوق";
    kiskustinoquruldi = "قىسقۇچتىن ئۆچۈرۈلدى";
    kiskusakoxuldi = "قىسقۇچقا قوشۇلدى";
    buangahirkisi = "بۇ ئەڭ ئاخىرقىسى";
    buangaldinkisi = "بۇ ئەڭ ئالدىنقىسى";
    keyinki = "كېيىنكى";
    aldinki = "ئالدىنقى";
    timilar = "تىمىلار";
    yok = "يوق";
    awarkiraatquxuring = "ئاۋال تەڭشەكتىن قىرائەت چۈشۈرۈپ، قىرائەتنى تاللاڭ";
    awalayattallang = "ئاۋال ئايەت تاللاڭ";
    keyinkiSura = "كېيىنكى سۈرە";
    server = "مۇلازىمىتىر";
    muyassarArabpa = "مۇيەسسەر(ئەرەپچە)";
    arjalalein = "جالالىيىن(ئەرەپچە)";
    muhtasarArapqa = "مۇختەسەر(ئەرەپچە)";
    muhtasar = "مۇختەسەر";
    muhtasarEnglish = "مۇختەسەر(ئىنگىلىزچە)";
    muhtasarChina = "مۇختەسەر(خەنزۇچە)";
    muhtasarTuruk = "مۇختەسەر(تۈرۈكچە)";
    ayatkatizberix = "ئايەتكە تىز بېرىش";
    arapqisinikorsitamdu = "ئەرەبچە تېكىستىنى كۆرسىتەمدۇ";
    ibnikasir = "ئىبنى كەسىر";
    muyassar = "مۇيەسسەر";
    zarif = "زەرىف";
    qiraattinioqurux = "قىرائەتنى ئۆچۈرۈش";
    qiraattinioqurux = "يۇۋېتىش";
    quxupbolgan = "چۈشۈپ بولغان";
    kiraatQuxurux = "قىرائەت چۈشۈرۈش";
    tallapquxurung = "چۈشۈرگەن قىرائەت يوق تۆۋەندىكىلەردىن تاللاپ چۈشۈرۈڭ";
    tallang = "تاللاڭ";
    haa = "ھەئە";
    saved = "ساقلاندى";
    quran = "قۇرئان";
    tepsir = "تەپسىر";
    oginix = "ئۆگۈنۈش";
    logat = "لوغەت";
    haptiyak = "ھەپتىيەك";
    para = "پارە";
    mundarija = "مۇندەرىجە";
    sura = "سۈرە";
    ayat = "ئايەت";
    tangxak = "تەڭشەك";
    kortisitiganTillar = "كۆرسىتىلىدىغان تەرجىمىلەر";
    arabikHatnurshisi = "ئەرەبچە خەت نۇسخىسى";
    hatnurshisi = "ئۇيغۇرچە خەت نۇسخىسى";
    language = "كۆرۈنۈش تىلى";
    hatqongliki = "ئەرەپچىنىڭ خەت چوڭلىقى";
    hatqonglikiUyghur = "باشقا خەت چوڭلىقى";
    kiraat = "قىرائەت";
    kaytix = "قايتىش";
    muahhmadsalih = "مۇھەممەد سالىھ تەرجىمىسى";
    hayattarjimisi = "ھەيئەت تەرجىمىسى";
    aalimTarjimiai = "ئە.ئالىم تەرجىمىسى";
    yusupmuhahmadtarjimisi = "مۇھەممەد يۈسۈپ تەرجىمىسى";
    muahhmadsalihMidel = "م.سالىھ";
    hayattarjimisiMidel = "ھەيئەت";
    aalimTarjimiaiMidel = "ئە.ئالىم";
    yusupmuhahmadtarjimisiMidel = "م.يۈسۈپ";
    hilTarjima = " خىل تەرجىمە";
    bismillaah = "بِسْمِ ٱللَّهِ ٱلرَّحْمَـٰنِ ٱلرَّحِيمِ";
    showTarjimaEnglish = "ئىنگىلىزچە تەرجىمىسى";
    showTarjimaTurky = "تۈرۈكچە تەرجىمىسى";
    showTarjimaHanyu = "خەنزۇچە تەرجىمىسى";
    assalam = "ئەسسالامۇئەلەيكۇم";
    sakliwalganlar = "قىسقۇچتىكىلەر";
    switch (lang) {
      case "zh-CN":
        haripboyqaizdax = "按字母搜搜";
        koquruldi = "已复制";
        hanzuqatapsir = "简明注释";
        tima = "菜单";
        angusti = "主页";
        qurandikimazmunlarniuginix = "古兰经主题";
        bax = "主菜单";
        muansiwatlikAyatlar = "内容";
        qurandikiTimilar = "古兰经主题";
        birayatkoyuxhalitigaalmaxti = "单节播放";
        kopyatkoyuxhalitigaalmaxti = "连续播放";
        bat = "页";
        rang = "颜色";
        naqijaTepildi = "个记录";
        kirixsoz = "前言";
        search = "搜       索";
        search1 = "搜索";
        dualar = "祈祷";
        marhaba = "欢迎";
        nosuraaya = "无法识别";
        tapsilatiniKuramsi = "要看详细内容吗？";
        jalalein = "Tafsir al-Jalalayn";
        aldinkiSaklapkoyganjaydinbaxlapokumsiz = "跳转上次的位置吗？";
        uqur = "提示";
        saklanganorunyok = "没有保存当前位置";
        okupkalganjaysaklandi = "当前位置已保存";
        saklangalaryok = "无收藏";
        kiskustinoquruldi = "删除收藏";
        kiskusakoxuldi = "已收藏";
        buangahirkisi = "这是最后一个";
        buangaldinkisi = "这是最第一个";
        keyinki = "下一个";
        aldinki = "上一个";
        timilar = "题目";
        yok = "无";
        awarkiraatquxuring = "请设置里下载诵读，选择诵读";
        awalayattallang = "请选择一个节";
        keyinkiSura = "下一章";
        server = "服务器";
        muyassarArabpa = "《古兰经注 Al-Muyassar(阿拉伯语)";
        arjalalein = "《古兰经注》Al-Jalalayn(阿拉伯语)";
        muhtasarArapqa = "《古兰经》简明经注(阿拉伯语)";
        muhtasar = "《古兰经》简明经注";
        muhtasarEnglish = "《古兰经》简明经注(英语)";
        muhtasarChina = "《古兰经》简明经注(中文)";
        muhtasarTuruk = "《古兰经》简明经注(土耳其语)";
        ayatkatizberix = "快速跳转";
        arapqisinikorsitamdu = "显示阿拉伯文";
        ibnikasir = "《古兰经注》伊本·凯西尔（维吾尔语）";
        muyassar = "古兰经注》 Al-Muyassar（维吾尔语）";
        zarif = "《古兰经注》Zarif (维吾尔语)";
        qiraattinioqurux = "删除诵读";
        qiraattinioqurux = "删除";
        quxupbolgan = "已下载";
        kiraatQuxurux = "诵读下载";
        tallapquxurung = "没有下载完成的诵读，请下面下载";
        tallang = "选择";
        haa = "是";
        saved = "已保存";
        quran = "古兰经";
        tepsir = "注释";
        oginix = "学习";
        logat = "词典";
        haptiyak = "诵读学简易教程";
        para = "卷";
        mundarija = "目录";
        sura = "章";
        ayat = "节";
        tangxak = "设置";
        kortisitiganTillar = "显示的翻译";
        arabikHatnurshisi = "阿拉伯字体";
        hatnurshisi = "维吾尔字体";
        language = "语言";
        hatqongliki = "阿拉伯字号";
        hatqonglikiUyghur = "其他字号";
        kiraat = "诵读";
        kaytix = "返回";
        muahhmadsalih = "穆哈迈德·萨力翻译";
        hayattarjimisi = "委员会翻译";
        aalimTarjimiai = "艾·阿里木翻译";
        yusupmuhahmadtarjimisi = "穆哈迈德·玉苏甫翻译";
        muahhmadsalihMidel = "穆·萨力";
        hayattarjimisiMidel = "委员会";
        aalimTarjimiaiMidel = "艾·阿里木";
        yusupmuhahmadtarjimisiMidel = "穆·玉苏甫";
        hilTarjima = " 种翻译";
        bismillaah = "بِسْمِ ٱللَّهِ ٱلرَّحْمَـٰنِ ٱلرَّحِيمِ";
        showTarjimaEnglish = "英语翻译";
        showTarjimaTurky = "土耳其翻译";
        showTarjimaHanyu = "中文翻译";
        assalam = "你好！";
        sakliwalganlar = "收藏";
        haa = "是";
        saved = "保存";
        quran = "古兰经";
        tepsir = "注释";
        oginix = "学习";
        logat = "词典";
        haptiyak = "阿拉伯语";
        break;
      case "en-US":
        haripboyqaizdax = "Search by letter";
        koquruldi = "Copied";
        haa = "Yes";
        saved = "saved";
        quran = "Quran";
        tepsir = "tepsir";
        oginix = "oginix";
        logat = "dict";
        haptiyak = "arabic";

        hanzuqatapsir = "Tefsir in Chinese";
        tima = "Title";
        angusti = "Top";
        qurandikimazmunlarniuginix = "Read Quran with title and Details";
        bax = "Home";
        muansiwatlikAyatlar = "Details ";
        qurandikiTimilar = "Title From Quran";
        birayatkoyuxhalitigaalmaxti = "Single Play";
        kopyatkoyuxhalitigaalmaxti = "Muilti Play";
        bat = "Page";
        rang = "Color";
        naqijaTepildi = "Sonuç bulamadım";
        kirixsoz = "ForeWords";
        search = "Search";
        search1 = "Search";
        dualar = "Dua's";
        marhaba = "Merhaba";
        nosuraaya = "Not Found Cuz and Ayet ";
        tapsilatiniKuramsi = "Details";
        jalalein = "Calalayin";
        aldinkiSaklapkoyganjaydinbaxlapokumsiz =
            "Do you play close on last time. ";
        uqur = "Note";
        saklanganorunyok = "Not fount last time play history";
        okupkalganjaysaklandi = "current play time is saved";
        saklangalaryok = "Not Found";
        kiskustinoquruldi = "Favorite Deleted";
        kiskusakoxuldi = "Favorit Saved";
        buangahirkisi = "This is End";
        buangaldinkisi = "This is First";
        keyinki = "Next ";
        aldinki = "Previous";
        timilar = "Title";
        yok = "Not Found";
        awarkiraatquxuring = "First download Voice then setting Voice";
        awalayattallang = "Choose the Cuz";
        keyinkiSura = "Next Cuz";
        server = "Servise";
        muyassarArabpa = "Muyesser(Arabic)";
        arjalalein = "Celaleyin(Arabic)";
        muhtasarArapqa = "Muhteser(Arabic)";
        muhtasar = "Muhtasar";
        muhtasarEnglish = "Muhteser(Enlish)";
        muhtasarChina = "Celaleyin(Chinese)";
        muhtasarTuruk = "Celaleyin(Turkey)";
        ayatkatizberix = "Open aya fast";
        arapqisinikorsitamdu = "Show Arabic Text";
        ibnikasir = "İbni kesir";
        muyassar = "Muyesser";
        zarif = "Zeref";
        qiraattinioqurux = "Delete voice";
        qiraattinioqurux = "Delete";
        quxupbolgan = "Donwloaded";
        kiraatQuxurux = "Download Quran Voice";
        tallapquxurung = "Not found voice,please download and choose";
        tallang = "Choose";
        haa = "Yes";
        saved = "Saved";
        quran = "Quran";
        tepsir = "Tefsir";
        oginix = "Study";
        logat = "Dictionary";
        haptiyak = "Quran Alphebet";
        para = "Cuz";
        mundarija = "Contents";
        sura = "Sura";
        ayat = "Aya";
        tangxak = "Ayar's";
        kortisitiganTillar = "Luanguage";
        arabikHatnurshisi = "Quran in Arabic";
        hatnurshisi = "Quran in Uyghur";
        language = "Languages";
        hatqongliki = "Arabic font size";
        hatqonglikiUyghur = "Other font size";
        kiraat = "Quran Voice";
        kaytix = "Back";
        muahhmadsalih = "Muhammed Salih Transilation";
        hayattarjimisi = "Hey'et Transilation";
        aalimTarjimiai = "E.Alim Transilation";
        yusupmuhahmadtarjimisi = "Muhammed Yusuf Transilation";
        muahhmadsalihMidel = "M.Salih";
        hayattarjimisiMidel = "Hey'et";
        aalimTarjimiaiMidel = "E.alim";
        yusupmuhahmadtarjimisiMidel = "M.Yusuf";
        hilTarjima = " Sort Transilation";
        bismillaah = "بِسْمِ ٱللَّهِ ٱلرَّحْمَـٰنِ ٱلرَّحِيمِ";
        showTarjimaEnglish = "English";
        showTarjimaTurky = "Turkish";
        showTarjimaHanyu = "Chinese";
        assalam = "As Selamun alyekum";
        sakliwalganlar = "Favortise";
        break;
      case "tr-TR":
        haripboyqaizdax = "Harf ile ara";
        koquruldi = "Kopyalandı";
        hanzuqatapsir = "Çince tefsir";
        tima = "Konu";
        angusti = "En üstü";
        qurandikimazmunlarniuginix = "Kuranı konu ve detailara göra öğrenin";
        bax = "Baş sayfa";
        muansiwatlikAyatlar = "Konuyla ilgili detailar";
        qurandikiTimilar = "Kurandaki konular";
        birayatkoyuxhalitigaalmaxti = "Tek ayeti çal";
        kopyatkoyuxhalitigaalmaxti = "Devamli çal";
        bat = "Sayfa";
        rang = "Rengk";
        naqijaTepildi = "Sonuç bulamadım";
        kirixsoz = "Ön söz";
        search = "Ara";
        search1 = "Ara";
        dualar = "Dualar";
        marhaba = "Merhaba";
        nosuraaya = "Cuz ve Ayeti bulamadı";
        tapsilatiniKuramsi = "Detailı görmek";
        jalalein = "Calalayin";
        aldinkiSaklapkoyganjaydinbaxlapokumsiz =
            "Önce kaldığınız yerden başlıyormusunuz?";
        uqur = "Not";
        saklanganorunyok = "Önce kaldığınız yer yok";
        okupkalganjaysaklandi = "Şimdi kaldığız yer kaydedildi";
        saklangalaryok = "Kayedilen Bulunmadı";
        kiskustinoquruldi = "Kay silindi";
        kiskusakoxuldi = "Kadedildi";
        buangahirkisi = "Bu sonuncusu ";
        buangaldinkisi = "Bu öncesi";
        keyinki = "Sonrası ";
        aldinki = "Öncesi";
        timilar = "Konular";
        yok = "Yok";
        awarkiraatquxuring =
            "Önce ayalardan kuran sesini indirip,sonra seçiniz";
        awalayattallang = "Önce Süryi seçiniz";
        keyinkiSura = "Sonraki Süre";
        server = "Servise";
        muyassarArabpa = "Muyesser(Arabça)";
        arjalalein = "Celaleyin(Arabça)";
        muhtasarArapqa = "Muhteser(Arabça)";
        muhtasar = "Muhtasar";
        muhtasarEnglish = "Muhteser(İngilizce)";
        muhtasarChina = "Celaleyin(Çince)";
        muhtasarTuruk = "Celaleyin(Türkçe)";
        ayatkatizberix = "Ayeti hızlı açmak";
        arapqisinikorsitamdu = "Arabça göstersin mi";
        ibnikasir = "İbni kesir";
        muyassar = "Muyesser";
        zarif = "Zeref";
        qiraattinioqurux = "Sesi silmek";
        qiraattinioqurux = "Sil";
        quxupbolgan = "İndirildi";
        kiraatQuxurux = "Kuran sesi indir";
        tallapquxurung = "İndirilen Ses yok,Seçip indiriniz";
        tallang = "Seç";
        haa = "Evet";
        saved = "Kaydedildi";
        quran = "Kuran";
        tepsir = "Tefsir";
        oginix = "Öğrenmek";
        logat = "Sözlük";
        haptiyak = "Kuran Kaidesi";
        para = "Cuz";
        mundarija = "Liste";
        sura = "Süre";
        ayat = "Ayat";
        tangxak = "Ayarlar";
        kortisitiganTillar = "Görünme dilleri";
        arabikHatnurshisi = "Arabça Kuran";
        hatnurshisi = "Uygurca fontlar";
        language = "Diller";
        hatqongliki = "Arabça yazı büyüklüğü";
        hatqonglikiUyghur = "Başka yazı büyüklüğü";
        kiraat = "Kuran sesi";
        kaytix = "Dön";
        muahhmadsalih = "Muhammed Salih Tercümesi";
        hayattarjimisi = "Heyet Tercümesi";
        aalimTarjimiai = "E.Alim Tercümesi";
        yusupmuhahmadtarjimisi = "Muhammed Yusuf Tercümesi";
        muahhmadsalihMidel = "M.Salih";
        hayattarjimisiMidel = "Hey'et";
        aalimTarjimiaiMidel = "E.alim";
        yusupmuhahmadtarjimisiMidel = "M.Yusuf";
        hilTarjima = " Çeşit Tercüme";
        bismillaah = "بِسْمِ ٱللَّهِ ٱلرَّحْمَـٰنِ ٱلرَّحِيمِ";
        showTarjimaEnglish = "İngilizce";
        showTarjimaTurky = "Türkçe";
        showTarjimaHanyu = "Çince";
        assalam = "As Selamun alyeküm";
        sakliwalganlar = "Kaydedilenler";
        break;

      case "ar-SA":
        haripboyqaizdax = "بحث بالحرف";
        koquruldi = "منسوخ";
        hanzuqatapsir = "ملاحظات موجزة";
        tima = "قائمة";
        angusti = "الصفحة الرئيسية";
        qurandikimazmunlarniuginix = "موضوع القرآن";
        bax = "القائمة الرئيسية";
        muansiwatlikAyatlar = "المحتوى";
        qurandikiTimilar = "موضوع القرآن";
        birayatkoyuxhalitigaalmaxti = "جلسة واحدة";
        kopyatkoyuxhalitigaalmaxti = "العب باستمرار";
        bat = "الصفحة";
        rang = "اللون";
        naqijaTepildi = "السجلات";
        kirixsoz = "مقدمة";
        search = "بحث";
        search1 = "بحث";
        dualar = "صلى";
        marhaba = "مرحبًا";
        nosuraaya = "غير معروف";
        tapsilatiniKuramsi = "هل تريد رؤية التفاصيل؟";
        jalalein = "تفسير الجلالين";
        aldinkiSaklapkoyganjaydinbaxlapokumsiz = "الانتقال إلى آخر موضع؟";
        uqur = "تلميح";
        saklanganorunyok = "لم يتم حفظ الموقع الحالي";
        okupkalganjaysaklandi = "تم حفظ الموقع الحالي";
        saklangalaryok = "لا توجد مفضلات";
        kiskustinoquruldi = "إزالة المفضلة";
        kiskusakoxuldi = "المفضلة";
        buangahirkisi = "هذا هو الأخير";
        buangaldinkisi = "هذا هو الأول";
        keyinki = "التالي";
        aldinki = "السابق";
        timilar = "العنوان";
        yok = "لا شيء";
        awarkiraatquxuring =
            "الرجاء تنزيل التلاوة في الإعدادات واختيار التلاوة";
        awalayattallang = "الرجاء تحديد قسم";
        keyinkiSura = "الفصل التالي";
        server = "الخادم";
        muyassarArabpa = "الميسر (عربي)";
        arjalalein = "الجلالين (عربي)";
        muhtasarArapqa = "شرح مختصر للقرآن (عربي)";
        muhtasar = "ملاحظات القرآن المختصرة";
        muhtasarEnglish = "شرح مختصر للقرآن (إنجليزي)";
        muhtasarChina = "ملاحظات موجزة على القرآن (صيني)";
        muhtasarTuruk = "شرح مختصر للقرآن (تركي)";
        ayatkatizberix = "انتقال سريع";
        arapqisinikorsitamdu = "عرض اللغة العربية";
        ibnikasir = "ملاحظات على القرآن لابن قصير";
        muyassar = "ملاحظات على القرآن الميسر (الأويغور)";
        zarif = "ظريف (أويغور)";
        qiraattinioqurux = "إزالة الترانيم";
        qiraattinioqurux = "حذف";
        quxupbolgan = "تم التنزيل";
        kiraatQuxurux = "تنزيل التلاوة";
        tallapquxurung = "ليست هناك قراءة مكتملة ، يرجى تنزيلها أدناه";
        tallang = "حدد";
        haa = "نعم";
        saved = "المحفوظة";
        quran = "القرآن";
        tepsir = "تعليق";
        oginix = "تعلم";
        logat = "القاموس";
        haptiyak = "دورة سهلة للقراءة";
        para = "لفة";
        mundarija = "دليل";
        sura = "سورة";
        ayat = "قسم";
        tangxak = "إعدادات";
        kortisitiganTillar = "عرض الترجمة";
        arabikHatnurshisi = "الخط العربي";
        hatnurshisi = "خط الأويغور";
        language = "اللغة";
        hatqongliki = "حجم الخط العربي";
        hatqonglikiUyghur = "حجم خط آخر";
        kiraat = "تلاوة";
        kaytix = "عودة";
        muahhmadsalih = "ترجمة محمد صالح";
        hayattarjimisi = "مترجم اللجنة";
        aalimTarjimiai = "ترجمة Ai Alimu";
        yusupmuhahmadtarjimisi = "ترجمة Muhammad Yusup";
        muahhmadsalihMidel = "مو صالح";
        hayattarjimisiMidel = "لجنة";
        aalimTarjimiaiMidel = "Ai Alimu";
        yusupmuhahmadtarjimisiMidel = "Mu · yusufu";
        hilTarjima = "ترجمة";
        bismillaah = "بِسْمِ ٱللَّهِ ٱلرَّحْمَـٰنِ ٱلرَّحِيمِ";
        showTarjimaEnglish = "الترجمة الإنجليزية";
        showTarjimaTurky = "الترجمة التركية";
        showTarjimaHanyu = "الترجمة الصينية";
        assalam = "مرحبًا!";
        sakliwalganlar = "المفضلة";
        haa = "نعم";
        saved = "المحفوظة";
        quran = "القرآن";
        tepsir = "تعليق";
        oginix = "تعلم";
        logat = "القاموس";
        haptiyak = "عربي";
        break;
    }
  }
}
